"""Photo routes: upload, Google Photos import, image serving."""
import asyncio
from typing import List

from fastapi import (
    APIRouter,
    BackgroundTasks,
    Depends,
    File,
    Header,
    HTTPException,
    Query,
    UploadFile,
)
from fastapi.responses import Response

from app.core.auth import decode_token, get_current_user
from app.core.executors import run_blocking
from app.db import db
from app.schemas import GooglePhotosImportInput
from app.services.albums import reject_if_ordered
from app.services.google_photos import import_google_photos_items
from app.services.photos import (
    generate_medium_variant,
    generate_print_variant,
    store_many_photos,
)
from app.services.processing import run_ai_processing_incremental
from app.services.storage import get_object

router = APIRouter()


@router.post("/albums/{album_id}/photos")
async def upload_photos(
    album_id: str,
    files: List[UploadFile] = File(...),
    user: dict = Depends(get_current_user),
):
    album = await db.albums.find_one({"id": album_id, "user_id": user["id"]})
    if not album:
        raise HTTPException(status_code=404, detail="Album introuvable")
    await reject_if_ordered(album_id)
    uploaded, truncated = await store_many_photos(album_id, user["id"], files)
    return {"uploaded": len(uploaded), "photos": uploaded, "limit_reached": truncated}

@router.post("/albums/{album_id}/import/google-photos")
async def import_google_photos(album_id: str, data: GooglePhotosImportInput, background_tasks: BackgroundTasks, user: dict = Depends(get_current_user)):
    album = await db.albums.find_one({"id": album_id, "user_id": user["id"]})
    if not album:
        raise HTTPException(status_code=404, detail="Album introuvable")
    await reject_if_ordered(album_id)

    uploaded, limit_reached = await import_google_photos_items(album_id, user["id"], data.items, data.access_token)

    # Mirrors the regular "add more photos" behavior exactly: only kick off
    # AI processing here if the album had already been through its first
    # AI pass before (the "editor" / add-more-later case). During the
    # creation wizard the album is still a fresh draft — photos just land
    # in the pool, and the wizard's own "Start AI" step processes
    # everything (this batch plus every other one) together, once.
    if uploaded and album.get("status") == "ready":
        await db.albums.update_one({"id": album_id}, {"$set": {"status": "processing"}})
        # Awaited, not background-tasked — same throttling issue as
        # /albums/{id}/process (see its comment). Each batch is already
        # small (~20 photos), so this stays quick even run inline.
        await run_ai_processing_incremental(album_id, user["id"], [p["id"] for p in uploaded])

    return {"uploaded": len(uploaded), "total": len(data.items), "limit_reached": limit_reached}

@router.get("/photos/{photo_id}/image")
async def get_photo_image(photo_id: str, auth: str = Query(None), authorization: str = Header(None), variant: str = Query("thumb")):
    # Support both header and query auth (for <img> tags)
    token = None
    if authorization and authorization.lower().startswith("bearer "):
        token = authorization.split(" ", 1)[1]
    elif auth:
        token = auth
    user_id = decode_token(token) if token else None
    if not user_id:
        raise HTTPException(status_code=401, detail="Not authenticated")
    photo = await db.photos.find_one({"id": photo_id, "user_id": user_id, "is_deleted": False})
    if not photo:
        raise HTTPException(status_code=404, detail="Photo introuvable")
    # "thumb" (small grids — the photo tray, upload picker) keeps browsing
    # fast; "medium" (the flipbook / editor page view) is sharp enough for
    # a full on-screen page without the cost of the full original;
    # "original" (used only by the PDF print page) always gets the
    # full-resolution file, since print quality must never be compromised.
    path = photo["storage_path"]
    served_content_type = photo.get("content_type")
    if variant == "thumb" and photo.get("thumbnail_path"):
        path = photo["thumbnail_path"]
        served_content_type = "image/jpeg"
    elif variant == "medium":
        if photo.get("medium_path"):
            # Already generated by an earlier request — no resizing work,
            # just serve the cached file like any other variant.
            path = photo["medium_path"]
            served_content_type = "image/jpeg"
        else:
            # First time this photo's medium size has ever been requested.
            # Generated here, on demand, rather than at upload time — most
            # of a large album's photos are never actually scrolled to in
            # the flipbook, so generating this for every photo up front
            # would waste time on pages nobody looks at. Cached to R2
            # afterwards so every subsequent view (this person or anyone
            # else) is an ordinary fast fetch, not a repeat resize.
            loop = asyncio.get_event_loop()
            medium_path, medium_bytes = await loop.run_in_executor(None, generate_medium_variant, photo)
            if medium_path:
                await db.photos.update_one({"id": photo_id}, {"$set": {"medium_path": medium_path}})
                path, served_content_type = medium_path, "image/jpeg"
                data = medium_bytes
                return Response(content=data, media_type=served_content_type, headers={"Cache-Control": "private, max-age=31536000, immutable"})
            # Fell through — resizing failed for some reason; serve the
            # thumbnail rather than the (much heavier) original as a safe
            # fallback so the page still renders something reasonable.
            if photo.get("thumbnail_path"):
                path, served_content_type = photo["thumbnail_path"], "image/jpeg"
    elif variant == "print":
        # Used only by the PDF export (PrintAlbum.jsx) — sized for genuine
        # print quality (PRINT_MAX_DIMENSION_PX) but not the raw original,
        # which was pushing the whole-album Playwright render past the
        # Cloud Run instance's memory limit. Same on-demand-then-cache
        # pattern as medium above.
        if photo.get("print_path"):
            path = photo["print_path"]
            served_content_type = "image/jpeg"
        else:
            loop = asyncio.get_event_loop()
            print_path, print_bytes = await loop.run_in_executor(None, generate_print_variant, photo)
            if print_path:
                await db.photos.update_one({"id": photo_id}, {"$set": {"print_path": print_path}})
                data = print_bytes
                return Response(content=data, media_type="image/jpeg", headers={"Cache-Control": "private, max-age=31536000, immutable"})
            # Resizing failed — fall back to the true original rather than
            # silently omitting the photo from the printed album.
    data, ctype = await run_blocking(get_object, path)
    return Response( content=data, media_type=served_content_type or ctype, headers={"Cache-Control": "private, max-age=31536000, immutable"}, )
